import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app.css";
import AddCategoryComponent from "./board/components/AddNewCategoryComponent";
import CategoryProviders from "./providers/CategoryProviders"; // Importa el CategoryProviders

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Budget Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <CategoryProviders>
          {" "}
          {/* Envuelve los children con CategoryProviders */}
          {children}
        </CategoryProviders>
      </body>
    </html>
  );
}
