import type { Metadata } from "next";
import "../app.css";
import CategoryProviders from "./providers/CategoryProviders";

export const metadata: Metadata = {
  title: "Budget Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <CategoryProviders>{children}</CategoryProviders>
      </body>
    </html>
  );
}
